apiVersion: v1
kind: Service
metadata:
  name: app-server-svc
spec:
  type: ClusterIP
  clusterIP: 10.102.254.116
  selector:
    app: app-server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
